# The various combinations of python and Django we test with
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - TOXENV=py3-django1.11
  - TOXENV=py3-django2.0
  - TOXENV=py3-django2.1
matrix:
  include:
    - python: "3.6"
      env: TOXENV=doc
    - python: "3.6"
      env: TOXENV=flake8
  exclude:
    - python: "3.4"
      env: TOXENV=py3-django2.1

install:
  - pip install tox codecov
# Test with "system" python and specified Django version
script:
  - tox -e ${TOXENV}
after_success:
  - codecov

# From: https://docs.travis-ci.com/user/deployment/pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build/doc/
    email: automation@uis.cam.ac.uk
    name: Automation Bot
    on:
      branch: master
      condition: $TOXENV = doc
